# Generated by Django 5.2.10 on 2026-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_name_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
