# Generated by Django 5.2.10 on 2026-02-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
